"""Authored (synthetic) sentences, part B: track signals and slot templates.

Track-signal sentences describe how someone might put an experience into words.
They are coverage seeds for the language layer and for regression tests. They are
not evidence that a person has a condition, and nothing here may set or change a
track (spec s79, s80). Psychosis sentences are written as attributed experience
("I feel like...") so replies can reflect without validating or disputing.
Dialect wording was written without a native reviewer.
"""

SIGNAL_TRACK = {
    "LOW_SLEEP_HIGH_ENERGY": "BIPOLAR", "RACING_THOUGHTS_PRESSURED_SPEECH": "BIPOLAR",
    "IMPULSIVE_SPENDING_PROJECTS": "BIPOLAR", "IRRITABILITY_ESCALATION": "BIPOLAR",
    "DEPRESSIVE_SLUMP": "BIPOLAR",
    "INITIATION_DIFFICULTY": "ADHD", "TIME_BLINDNESS": "ADHD", "DISTRACTIBILITY": "ADHD",
    "TASK_OVERWHELM": "ADHD", "EMOTIONAL_DYSREGULATION": "ADHD",
    "REFERENTIAL_PARANOID_FEELING": "SCHIZOPHRENIA",
    "PERCEPTUAL_EXPERIENCE_REPORT": "SCHIZOPHRENIA",
    "MEDICATION_STOPPING_MENTION": "SCHIZOPHRENIA",
    "DISORGANISED_THINKING_REPORT": "SCHIZOPHRENIA",
    "SLEEP_LOSS_WITHDRAWAL": "SCHIZOPHRENIA",
    "NONE": "NONE",
}

SIGNALS = {
    "LOW_SLEEP_HIGH_ENERGY": {
        "en": ["i've only slept two hours but i feel amazing",
               "i don't need sleep anymore, i'm full of energy",
               "i slept three hours and i'm buzzing",
               "haven't slept in two nights and i've never felt so alive",
               "i'm wide awake at 4am and ready to take on the world",
               "sleep feels like a waste of time right now",
               "i only needed four hours and i feel unstoppable",
               "i woke up after two hours of sleep full of energy"],
        "MSA": ["نمت ساعتين فقط ومع ذلك أشعر بنشاط هائل",
                "لم أعد أحتاج إلى النوم، أشعر بطاقة كبيرة",
                "نمت ثلاث ساعات وأنا في قمة النشاط",
                "لم أنم منذ ليلتين ولم أشعر بالحيوية هكذا من قبل",
                "أنا مستيقظ عند الرابعة فجراً ومستعد لأي شيء",
                "النوم يبدو مضيعة للوقت الآن"],
        "GLF": ["نمت ساعتين بس وحاس بطاقة مو طبيعية", "ما عاد أحتاج نوم، مليان نشاط",
                "ما نمت ليلتين وحاس إني أقوى من قبل", "صحيت الفجر ومليان حيوية"],
        "EGY": ["نمت ساعتين بس وحاسس إني فل", "مبقتش محتاج أنام، مليان طاقة"],
        "LEV": ["نمت ساعتين بس وحاسس حالي نشيط كتير", "ما عاد بدي نام، عندي طاقة كبيرة"],
        "FRANCO": ["nemt sa3tein bas w ana nasheet ktir", "ma 3ad badi nam 3ndi taqa kbeera"],
    },
    "RACING_THOUGHTS_PRESSURED_SPEECH": {
        "en": ["my mind is racing with a hundred ideas tonight",
               "my thoughts are moving so fast i can't keep up with them",
               "i've been talking so fast that people can't follow me",
               "i can't stop talking, words just keep pouring out",
               "ideas keep jumping from one thing to another and i can't slow down",
               "i have so many thoughts at once that i can't finish a sentence",
               "my brain won't slow down, it feels like a race",
               "i keep interrupting people because my thoughts are too fast"],
        "MSA": ["أفكاري تتسارع الليلة ومعي مئة فكرة", "أفكاري أسرع مما أستطيع ملاحقته",
                "أتكلم بسرعة حتى لا يستطيع الناس مجاراتي", "لا أستطيع التوقف عن الكلام",
                "تقفز الأفكار من شيء إلى آخر ولا أستطيع الإبطاء",
                "عقلي لا يتباطأ، وكأنه سباق"],
        "GLF": ["راسي مليان أفكار وما يوقف", "أتكلم بسرعة والناس ما تلحقني",
                "أفكاري تركض وما أقدر أبطيها", "ما أقدر أسكت، الكلام يطلع لحاله"],
        "EGY": ["دماغي بتجري بسرعة ومش قادر أوقفها", "بتكلم بسرعة والناس مش بتلحقني"],
        "LEV": ["أفكاري عم تركض وما فيني وقفها", "عم احكي بسرعة والناس ما عم تلحقني"],
        "FRANCO": ["afkari tarkod w ma ader abattiha", "batkallam bsor3a w el nas ma talha2ni"],
    },
    "IMPULSIVE_SPENDING_PROJECTS": {
        "en": ["i've started five new projects this week and i'm not stopping",
               "i spent way more than i planned because it felt right",
               "i bought things i don't need and it felt great at the time",
               "i'm quitting my job to start a business tomorrow, i just know it'll work",
               "i signed up for three courses today and i'm planning more",
               "i keep making big plans and spending money on them",
               "i had a brilliant idea and put a lot of money into it straight away",
               "i've been taking on more and more commitments and i can't say no"],
        "MSA": ["بدأت خمسة مشاريع جديدة هذا الأسبوع ولا أريد التوقف",
                "صرفت أكثر بكثير مما خططت لأن الأمر بدا صائباً",
                "اشتريت أشياء لا أحتاجها وشعرت بأنه أمر رائع",
                "سأترك عملي لأبدأ مشروعاً غداً وأنا واثق أنه سينجح",
                "سجلت في ثلاث دورات اليوم وأخطط للمزيد",
                "تأتيني فكرة رائعة فأضخ فيها الكثير من المال فوراً"],
        "GLF": ["بديت خمس مشاريع هالأسبوع وما أبي أوقف", "صرفت فلوس أكثر من اللي خططت له",
                "اشتريت أشياء ما أحتاجها وكنت مبسوط",
                "بترك شغلي وأبدأ مشروع بكرة وأنا متأكد إنه بينجح"],
        "EGY": ["بدأت خمس مشاريع الأسبوع ده ومش عايز أقف",
                "صرفت فلوس أكتر بكتير من اللي خططت له"],
        "LEV": ["بلشت خمس مشاريع هالأسبوع وما بدي وقف",
                "صرفت مصاري أكتر بكتير من يلي خططتلو"],
        "FRANCO": ["bdeit khamsa mashare3 hal esboo3 w ma abghi awqaf",
                   "sarafet floos akthar men elli khattatt lah"],
    },
    "IRRITABILITY_ESCALATION": {
        "en": ["everyone is getting on my nerves and i snap at them",
               "i lost my temper over something tiny today",
               "i can't stand being around people, they're so slow",
               "i'm so irritable that i'm arguing with everyone",
               "little things are making me furious",
               "i keep raising my voice and then regretting it",
               "my patience is gone and i'm picking fights",
               "i'm angry at everything and i don't know why"],
        "MSA": ["الجميع يستفزني وأنفعل عليهم", "فقدت أعصابي اليوم بسبب أمر تافه",
                "لا أحتمل وجود الناس حولي، إنهم بطيئون",
                "أنا سريع الانفعال وأتجادل مع الجميع", "الأشياء الصغيرة تغضبني بشدة",
                "أرفع صوتي ثم أندم"],
        "GLF": ["الكل يعصبني وأنفجر عليهم", "طفشت من الناس وأتعارك مع الكل",
                "أي شي صغير يعصبني", "أرفع صوتي وبعدين أندم"],
        "EGY": ["كله بيعصبني وبنفجر فيهم", "أي حاجة صغيرة بتخليني أتعصب"],
        "LEV": ["كل الناس عم تعصبني وبنفجر فيهم", "أي شي زغير بيعصبني"],
        "FRANCO": ["el koll ye3asabni w anfejer 3alehom", "ay shi sagheer ye3asabni"],
    },
    "DEPRESSIVE_SLUMP": {
        "en": ["i can't get out of bed and nothing feels worth doing",
               "i've been sleeping twelve hours and i'm still exhausted",
               "the energy i had last week is gone and everything feels grey",
               "i have no interest in anything anymore",
               "i feel empty and i've stopped answering messages",
               "i can't concentrate and everything feels heavy",
               "i feel flat and numb", "i've been crying and i can't say why"],
        "MSA": ["لا أستطيع النهوض من السرير ولا شيء يستحق العناء",
                "أنام اثنتي عشرة ساعة وما زلت منهكاً",
                "الطاقة التي كانت عندي الأسبوع الماضي اختفت وكل شيء رمادي",
                "لم أعد مهتماً بأي شيء", "أشعر بالفراغ وتوقفت عن الرد على الرسائل",
                "أشعر بالبلادة والخدر"],
        "GLF": ["ما أقدر أقوم من السرير وما أشوف شي يستاهل", "أنام اثنعش ساعة وأنا تعبان",
                "الطاقة اللي كانت عندي راحت وكل شي رمادي", "ما عاد يهمني شي"],
        "EGY": ["مش قادر أقوم من السرير ولا حاجة تستاهل", "بنام اتناشر ساعة ولسه تعبان"],
        "LEV": ["ما فيني قوم من التخت وما في شي يستاهل", "عم نام اثنعش ساعة ولسا تعبان"],
        "FRANCO": ["ma a2der a2oom men el sareer", "nemt ethna3shar sa3a w lessa ta3ban"],
    },
    "INITIATION_DIFFICULTY": {
        "en": ["i know what i need to do but i just can't start",
               "i've been staring at the task for an hour without starting",
               "starting anything feels impossible even when it's simple",
               "i keep putting off the one thing i need to do",
               "i sit down to work and end up doing nothing",
               "the first step feels like a wall",
               "i can't make myself begin even though the deadline is close",
               "i'm stuck at the starting line again"],
        "MSA": ["أعرف ما يجب أن أفعله لكنني لا أستطيع البدء",
                "أحدق في المهمة منذ ساعة دون أن أبدأ",
                "البدء في أي شيء يبدو مستحيلاً حتى لو كان بسيطاً",
                "أؤجل الشيء الوحيد الذي يجب أن أفعله", "أجلس للعمل ثم لا أفعل شيئاً",
                "لا أستطيع أن أجبر نفسي على البدء رغم قرب الموعد النهائي"],
        "GLF": ["أدري شو لازم أسوي بس ما أقدر أبدأ", "صار لي ساعة أطالع المهمة وما بديت",
                "أي شي بسيط أحس إن بدايته مستحيلة", "أأجل الشي اللي لازم أسويه"],
        "EGY": ["عارف المفروض أعمل إيه بس مش قادر أبدأ",
                "بقالي ساعة ببص في الشغل وماعملتش حاجة"],
        "LEV": ["بعرف شو لازم عمل بس ما فيني بلش", "صرلي ساعة عم طالع بالمهمة وما بلشت"],
        "FRANCO": ["a3ref lazem a3mal eh bas mesh adir abda2",
                   "ba2alli sa3a bbos fel shoghl w ma 3amalt haga"],
    },
    "TIME_BLINDNESS": {
        "en": ["i thought it had been ten minutes but two hours went by",
               "i'm late again because i lost track of time",
               "i keep underestimating how long things take",
               "i looked up and it was already evening",
               "i completely forgot about the meeting until it was over",
               "time just disappears when i start something",
               "i always think i have more time than i do",
               "i missed the deadline because i didn't notice the days passing"],
        "MSA": ["ظننت أنها عشر دقائق لكن مرت ساعتان", "تأخرت مجدداً لأنني فقدت الإحساس بالوقت",
                "أستخف دائماً بالوقت الذي تستغرقه الأشياء", "رفعت رأسي فإذا هو المساء",
                "نسيت الاجتماع تماماً حتى انتهى", "الوقت يختفي حين أبدأ في شيء"],
        "GLF": ["حسبتها عشر دقايق وراحت ساعتين", "تأخرت مرة ثانية لأني ما حسيت بالوقت",
                "دايم أقلل من الوقت اللي تاخذه الأشياء", "نسيت الاجتماع لين خلص"],
        "EGY": ["افتكرتها عشر دقايق وعدّت ساعتين", "اتأخرت تاني عشان مخدتش بالي من الوقت"],
        "LEV": ["فكرتها عشر دقايق ومرقو ساعتين", "تأخرت مرة تانية لأنو ما حسيت بالوقت"],
        "FRANCO": ["7asabtha 3ashar da2ayi2 w marrat sa3tein",
                   "t2akhart marra thanya la2ni ma 7asset bel wa2t"],
    },
    "DISTRACTIBILITY": {
        "en": ["i keep getting pulled away from what i'm doing by everything around me",
               "i read the same page five times and nothing stuck",
               "my attention jumps to something else every few minutes",
               "i started cleaning, then cooking, then something else, and finished nothing",
               "i can't stay focused on a conversation for more than a minute",
               "every little noise breaks my concentration",
               "i open my phone for one thing and forget what i was doing",
               "my mind keeps wandering while i work"],
        "MSA": ["ينجرف انتباهي عما أفعله بكل ما حولي", "قرأت الصفحة نفسها خمس مرات ولم يعلق شيء",
                "ينتقل انتباهي إلى شيء آخر كل بضع دقائق",
                "بدأت أنظف ثم أطبخ ثم شيئاً آخر ولم أنهِ أي شيء",
                "لا أستطيع التركيز في حديث أكثر من دقيقة",
                "كل ضوضاء صغيرة تقطع تركيزي"],
        "GLF": ["انتباهي يروح لأي شي حولي", "قريت نفس الصفحة خمس مرات وما علق شي",
                "بديت أنظف وبعدين أطبخ وما خلصت شي", "ما أقدر أركز بالكلام أكثر من دقيقة"],
        "EGY": ["تركيزي بيشرد مع أي حاجة حواليا",
                "قريت نفس الصفحة خمس مرات ومفيش حاجة علقت"],
        "LEV": ["تركيزي بيروح عأي شي حواليي", "قريت نفس الصفحة خمس مرات وما علق شي"],
        "FRANCO": ["tarkizi yrouh la ay shi", "2arayt nafs el safha khams marrat"],
    },
    "TASK_OVERWHELM": {
        "en": ["i have ten things to do and i'm doing none of them",
               "my to-do list is so long that i don't know where to begin",
               "every task feels equally urgent and i freeze",
               "i keep adding tasks and never finishing any",
               "everything on my list is half done",
               "the pile of tasks makes me want to hide from all of it",
               "i can't decide what to do first so i do nothing",
               "there's so much waiting for me that i avoid looking at it"],
        "MSA": ["لدي عشرة أشياء لأفعلها ولا أفعل أياً منها",
                "قائمة مهامي طويلة لدرجة أنني لا أعرف من أين أبدأ",
                "كل مهمة تبدو عاجلة بالقدر نفسه فأتجمد",
                "أواصل إضافة المهام ولا أنهي أياً منها", "كل ما في قائمتي نصف منجز",
                "لا أستطيع أن أقرر ما الذي أفعله أولاً فلا أفعل شيئاً"],
        "GLF": ["عندي عشر أشياء أسويها وما سويت ولا وحدة",
                "قائمة مهامي طويلة وما أدري من وين أبدأ", "كل شي يبدو مستعجل فأتجمد",
                "كل شي عندي نص منجز"],
        "EGY": ["عندي عشر حاجات أعملها ومعملتش ولا واحدة",
                "قايمة الشغل طويلة ومش عارف أبدأ منين"],
        "LEV": ["عندي عشر أشيا لعملهن وما عملت ولا وحدة",
                "لايحة المهام طويلة وما بعرف من وين بلش"],
        "FRANCO": ["3indi 3ashar ashya w ma 3amalt wala wa7da",
                   "2a2emet el mohem tawila w ma a3ref men ween abda2"],
    },
    "EMOTIONAL_DYSREGULATION": {
        "en": ["a small comment ruined my whole day and i couldn't calm down",
               "my feelings go from fine to furious in seconds",
               "i cried over something minor and couldn't stop",
               "i snapped at someone and regretted it right away",
               "criticism hits me so hard that i shut down",
               "my emotions feel too big for the situation",
               "i get so frustrated so quickly when things don't work",
               "i can't shake the feeling after a small setback"],
        "MSA": ["تعليق صغير أفسد يومي كله ولم أستطع الهدوء",
                "مشاعري تنتقل من الهدوء إلى الغضب في ثوانٍ",
                "بكيت من أمر بسيط ولم أستطع التوقف", "انفعلت على شخص وندمت فوراً",
                "النقد يؤثر فيّ بشدة حتى أنغلق", "مشاعري أكبر من الموقف"],
        "GLF": ["كلمة صغيرة خربت يومي كله وما قدرت أهدأ",
                "مشاعري تتغير من عادي لغضب في ثواني", "أي انتقاد يأثر فيني وأسكر على نفسي",
                "أعصب بسرعة إذا الأمور ما تمشي"],
        "EGY": ["كلمة صغيرة باظت يومي كله ومقدرتش أهدى",
                "مشاعري بتتغير من عادي لغضب في ثواني"],
        "LEV": ["كلمة زغيرة خربت يومي كله وما قدرت إهدى",
                "مشاعري بتتغير من عادي لغضب بثواني"],
        "FRANCO": ["kelma sagheera kharabat yawmi", "mash3eri betet8ayar men 3adi la ghadab"],
    },
    "REFERENTIAL_PARANOID_FEELING": {
        "en": ["i feel like people are watching me when i go outside",
               "it seems like the neighbours are talking about me",
               "i feel like someone is following me",
               "it feels like strangers know things about me",
               "i keep thinking my phone is being monitored",
               "it feels like there are signs meant for me on the news",
               "i'm worried that people at work are plotting against me",
               "i feel like they're listening to my conversations"],
        "MSA": ["أشعر أن الناس يراقبونني حين أخرج", "يبدو لي أن الجيران يتحدثون عني",
                "أشعر أن أحداً يتبعني", "أشعر أن الغرباء يعرفون أشياء عني",
                "أظل أفكر أن هاتفي تحت المراقبة", "أشعر أن هناك رسائل موجهة لي في الأخبار"],
        "GLF": ["أحس إن الناس يراقبوني إذا طلعت", "أحس إن الجيران يتكلمون عني",
                "أحس إن أحد يتبعني", "أحس إن جوالي مراقب"],
        "EGY": ["حاسس إن الناس بتراقبني لما أنزل", "حاسس إن الجيران بيتكلموا عني"],
        "LEV": ["حاسس إنو الناس عم تراقبني لما بطلع", "حاسس إنو في حدا عم يتبعني"],
        "FRANCO": ["7ases en el nas betraqebni", "7ases enno fi 7ada 3am yetba3ni"],
    },
    "PERCEPTUAL_EXPERIENCE_REPORT": {
        "en": ["i heard someone call my name but nobody was there",
               "i keep hearing a voice when i'm alone",
               "i saw something in the corner of the room that wasn't there",
               "the voices got louder last night", "i hear whispering when it's quiet",
               "i keep smelling something that nobody else can",
               "i heard music playing that no one else heard",
               "sometimes i hear comments about what i'm doing"],
        "MSA": ["سمعت أحداً ينادي اسمي ولم يكن هناك أحد", "أسمع صوتاً باستمرار حين أكون وحدي",
                "رأيت شيئاً في زاوية الغرفة لم يكن موجوداً", "ارتفعت الأصوات ليلة أمس",
                "أسمع همساً حين يكون المكان هادئاً", "أشم رائحة لا يشمها غيري"],
        "GLF": ["سمعت أحد يناديني وما كان أحد موجود", "أسمع صوت كل ما أكون وحدي",
                "الأصوات ارتفعت أمس بالليل", "أسمع همس إذا الجو هادي"],
        "EGY": ["سمعت حد بيناديني ومكانش فيه حد", "الأصوات علت امبارح بالليل"],
        "LEV": ["سمعت حدا عم ينادي اسمي وما كان في حدا", "الأصوات علت البارحة بالليل"],
        "FRANCO": ["sme3t 7ada yenadini w ma kan fi 7ada", "el aswat 3elyet el barha"],
    },
    "MEDICATION_STOPPING_MENTION": {
        "en": ["i stopped taking my medication because i feel fine now",
               "i've been skipping my pills this week",
               "i don't think i need my medication anymore",
               "i ran out of my medication a few days ago",
               "i only take my tablets when i remember",
               "my medication makes me feel slow so i've stopped it",
               "i forgot my medication for three days",
               "i decided to cut my dose without telling my doctor"],
        "MSA": ["توقفت عن تناول دوائي لأنني أشعر بتحسن", "أتجاوز جرعات دوائي هذا الأسبوع",
                "لا أظن أنني أحتاج الدواء بعد الآن", "نفد دوائي منذ أيام",
                "أتناول الحبوب فقط حين أتذكر", "الدواء يجعلني بطيئاً فتوقفت عنه"],
        "GLF": ["وقفت الدواء لأني أحس إني بخير", "أنسى حبوبي هالأسبوع",
                "ما أظن أحتاج الدواء بعد", "خلص دوائي من كم يوم"],
        "EGY": ["وقفت الدوا لأني حاسس إني كويس", "بنسى الدوا الأسبوع ده"],
        "LEV": ["وقفت الدوا لأني حاسس حالي منيح", "بنسى الحبوب هالأسبوع"],
        "FRANCO": ["wa2aft el dawa la2ani a7es ani bekhair", "ansa el dawa hal esboo3"],
    },
    "DISORGANISED_THINKING_REPORT": {
        "en": ["my thoughts feel jumbled and i can't follow them",
               "i lose my train of thought in the middle of a sentence",
               "everything i think feels tangled up",
               "i can't connect my thoughts together today",
               "my mind feels foggy and scattered",
               "people say i'm jumping between topics and i can't tell",
               "it's hard to think clearly, my thoughts get cut off",
               "i can't organise what i want to say"],
        "MSA": ["أفكاري مشوشة ولا أستطيع تتبعها", "أفقد سلسلة أفكاري في منتصف الجملة",
                "كل ما أفكر فيه يبدو متشابكاً", "لا أستطيع ربط أفكاري اليوم",
                "ذهني ضبابي ومتناثر", "من الصعب أن أفكر بوضوح، تنقطع أفكاري"],
        "GLF": ["أفكاري مخربطة وما أقدر أتابعها", "أضيع بنص الجملة",
                "ما أقدر أربط أفكاري اليوم", "راسي ضباب"],
        "EGY": ["أفكاري مش مترتبة ومش قادر أمسكها", "بنسى اللي كنت بقوله في نص الجملة"],
        "LEV": ["أفكاري مشوشة وما فيني تابعها", "بضيع بنص الجملة"],
        "FRANCO": ["afkari moshawasha w ma a2der ataba3ha", "badee3 bi nos el jomla"],
    },
    "SLEEP_LOSS_WITHDRAWAL": {
        "en": ["i haven't slept properly in days and i've stopped seeing anyone",
               "i've been staying in my room and avoiding everyone",
               "i stopped answering calls and i'm barely sleeping",
               "i can't sleep and i don't want to be around people",
               "i've been awake most nights and i've cut off my friends",
               "i've stayed inside all week and my sleep is a mess",
               "i don't want to see anyone and i'm awake all night",
               "i've stopped going out and i'm sleeping badly"],
        "MSA": ["لم أنم جيداً منذ أيام وتوقفت عن رؤية أي شخص",
                "أبقى في غرفتي وأتجنب الجميع", "توقفت عن الرد على المكالمات وبالكاد أنام",
                "لا أستطيع النوم ولا أريد أن أكون بين الناس",
                "أسهر أغلب الليالي وقطعت صلتي بأصدقائي",
                "بقيت في البيت طوال الأسبوع ونومي مضطرب"],
        "GLF": ["ما نمت زين من أيام وما عدت أشوف أحد", "أقعد في غرفتي وأتجنب الكل",
                "وقفت أرد على المكالمات وبالكاد أنام", "ما أبغى أشوف أحد وساهر كل الليل"],
        "EGY": ["مش عارف أنام من أيام وبطلت أشوف حد", "قاعد في أوضتي وبتجنب الكل"],
        "LEV": ["ما نمت منيح من أيام وبطلت شوف حدا", "قاعد بغرفتي وعم تجنب الكل"],
        "FRANCO": ["ma nemt mnee7 men ayam w batalet shoof 7ada",
                   "a3id bi ghorfti w 3am atjannab el koll"],
    },
    "NONE": {
        "en": ["i had a productive day and finished my tasks", "work was fine and i went for a walk",
               "i slept well and feel rested", "i had lunch with a friend",
               "we watched a film and went to bed early", "i'm planning my weekend",
               "the weather was nice today", "i cooked dinner and called my mother",
               "i'm a bit tired but it was a normal day", "my day was quiet and pleasant",
               "i finished a book this evening", "i went to the gym and then relaxed"],
        "MSA": ["كان يوماً منتجاً وأنهيت مهامي", "كان العمل عادياً وخرجت للتمشي",
                "نمت جيداً وأشعر بالراحة", "تناولت الغداء مع صديق",
                "شاهدنا فيلماً ونمنا مبكراً", "أخطط لعطلة نهاية الأسبوع",
                "كان الطقس جميلاً اليوم", "طبخت العشاء واتصلت بوالدتي",
                "أنا متعب قليلاً لكنه كان يوماً عادياً", "كان يومي هادئاً ولطيفاً"],
        "GLF": ["يومي كان عادي وخلصت شغلي", "نمت زين وحاس بالراحة", "تغدينا مع الربع",
                "الجو كان حلو اليوم", "طبخت العشا واتصلت بأمي"],
        "EGY": ["يومي كان عادي وخلصت شغلي", "نمت كويس وحاسس بالراحة"],
        "LEV": ["يومي كان عادي وخلصت شغلي", "نمت منيح وحاسس بالراحة"],
        "FRANCO": ["yawmi kan 3adi", "nemt kwayyes w ana murtaha"],
    },
}

# ---------------------------------------------------------------------------
# Slot templates. {n} numeric, {h} Arabic hours phrase. One template = one group.
# ---------------------------------------------------------------------------
EN_NUM_WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six",
                7: "seven", 8: "eight", 9: "nine", 10: "ten"}

AR_HOURS = {1: "ساعة واحدة", 2: "ساعتين", 3: "ثلاث ساعات", 4: "أربع ساعات",
            5: "خمس ساعات", 6: "ست ساعات", 7: "سبع ساعات", 8: "ثماني ساعات",
            9: "تسع ساعات", 10: "عشر ساعات"}
AR_TASKS = {2: "مهمتين", 3: "ثلاث مهام", 4: "أربع مهام", 5: "خمس مهام", 6: "ست مهام",
            7: "سبع مهام", 8: "ثماني مهام", 9: "تسع مهام", 10: "عشر مهام"}
EASTERN = str.maketrans("0123456789", "٠١٢٣٤٥٦٧٨٩")

SLOT_NUMERIC = [
    # (slot, lang, dialect, template, rendering)   rendering: digit | word | ar_hours | ar_tasks
    ("sleep_hours", "en", "EN", "i slept {n} hours last night", "digit"),
    ("sleep_hours", "en", "EN", "only got {n} hours of sleep", "digit"),
    ("sleep_hours", "en", "EN", "slept about {n} hours", "digit"),
    ("sleep_hours", "en", "EN", "{n} hours of sleep last night", "digit"),
    ("sleep_hours", "en", "EN", "i slept {n} hours and woke up early", "word"),
    ("sleep_hours", "en", "EN", "got {n} hours of sleep", "word"),
    ("sleep_hours", "ar", "MSA", "نمت {h} الليلة الماضية", "ar_hours"),
    ("sleep_hours", "ar", "MSA", "لم أنم سوى {h}", "ar_hours"),
    ("sleep_hours", "ar", "MSA", "نمت {n} ساعات فقط", "digit_ar"),
    ("sleep_hours", "ar", "GLF", "نمت {h} بس", "ar_hours"),
    ("sleep_hours", "ar", "GLF", "ما نمت إلا {h}", "ar_hours"),
    ("sleep_hours", "ar", "EGY", "نمت {h} بس امبارح", "ar_hours"),
    ("sleep_hours", "ar", "EGY", "منمتش غير {h}", "ar_hours"),
    ("sleep_hours", "ar", "LEV", "نمت {h} بس البارحة", "ar_hours"),
    ("energy", "en", "EN", "my energy is {n} out of 10", "digit"),
    ("energy", "en", "EN", "energy {n}/10 today", "digit"),
    ("energy", "en", "EN", "i'd say my energy is a {n}", "digit"),
    ("energy", "ar", "MSA", "طاقتي {n} من 10", "digit"),
    ("energy", "ar", "MSA", "طاقتي اليوم {n} من عشرة", "digit_ar"),
    ("energy", "ar", "GLF", "طاقتي {n} من 10 اليوم", "digit"),
    ("energy", "ar", "EGY", "طاقتي {n} من 10", "digit"),
    ("mood", "en", "EN", "my mood is about a {n}", "digit"),
    ("mood", "en", "EN", "mood {n}/10", "digit"),
    ("mood", "en", "EN", "my mood is {n} out of 10 today", "digit"),
    ("mood", "ar", "MSA", "مزاجي {n} من 10", "digit"),
    ("mood", "ar", "MSA", "مزاجي اليوم {n} من عشرة", "digit_ar"),
    ("mood", "ar", "GLF", "مزاجي {n}/10", "digit"),
    ("mood", "ar", "LEV", "مزاجي {n} من 10", "digit"),
    ("stress", "en", "EN", "my stress is {n} out of 10", "digit"),
    ("stress", "en", "EN", "stress level {n}/10", "digit"),
    ("stress", "ar", "MSA", "توتري {n} من 10", "digit"),
    ("stress", "ar", "GLF", "ضغطي النفسي {n} من 10", "digit"),
    ("tasks_count", "en", "EN", "i have {n} things to do today", "digit"),
    ("tasks_count", "en", "EN", "{n} tasks on my list and i haven't started", "digit"),
    ("tasks_count", "en", "EN", "i've got {n} deadlines this week", "digit"),
    ("tasks_count", "ar", "MSA", "لدي {h} اليوم", "ar_tasks"),
    ("tasks_count", "ar", "GLF", "عندي {n} أشياء لازم أنجزها", "digit"),
    ("tasks_count", "ar", "EGY", "عندي {n} حاجات أعملها النهاردة", "digit"),
    ("alcohol_drinks", "en", "EN", "i had {n} drinks last night", "digit"),
    ("alcohol_drinks", "en", "EN", "i drank {n} beers with dinner", "word"),
]

# Boolean slots: (slot, value, lang, dialect, sentence)
SLOT_BOOLEAN = [
    ("meds_taken", True, "en", "EN", "i took my medication this morning"),
    ("meds_taken", True, "en", "EN", "took my meds as usual"),
    ("meds_taken", True, "en", "EN", "i've taken my pills today"),
    ("meds_taken", False, "en", "EN", "i forgot my medication today"),
    ("meds_taken", False, "en", "EN", "i skipped my meds last night"),
    ("meds_taken", False, "en", "EN", "i haven't taken my pills today"),
    ("meds_taken", False, "en", "EN", "i missed my dose this morning"),
    ("meds_taken", True, "ar", "MSA", "تناولت دوائي هذا الصباح"),
    ("meds_taken", True, "ar", "MSA", "أخذت أدويتي كالمعتاد"),
    ("meds_taken", True, "ar", "GLF", "أخذت دوائي اليوم"),
    ("meds_taken", False, "ar", "MSA", "نسيت دوائي اليوم"),
    ("meds_taken", False, "ar", "MSA", "فوّتُّ جرعة الصباح"),
    ("meds_taken", False, "ar", "GLF", "ما أخذت حبوبي اليوم"),
    ("meds_taken", False, "ar", "EGY", "مأخدتش الدوا النهاردة"),
    ("spending_unplanned", True, "en", "EN", "i spent a lot of money on stuff i don't need today"),
    ("spending_unplanned", True, "en", "EN", "i bought several things online tonight that i hadn't planned"),
    ("spending_unplanned", True, "en", "EN", "i overspent again this weekend"),
    ("spending_unplanned", True, "ar", "MSA", "صرفت مبلغاً كبيراً على أشياء لا أحتاجها اليوم"),
    ("spending_unplanned", True, "ar", "MSA", "اشتريت أشياء كثيرة لم أخطط لها"),
    ("spending_unplanned", True, "ar", "GLF", "صرفت وايد على أشياء ما أحتاجها"),
    ("spending_unplanned", True, "ar", "EGY", "صرفت فلوس كتير على حاجات مش محتاجها"),
    ("social_contact", False, "en", "EN", "i haven't talked to anyone today"),
    ("social_contact", False, "en", "EN", "i didn't see anyone all day"),
    ("social_contact", False, "en", "EN", "i stayed home alone all day"),
    ("social_contact", True, "en", "EN", "i had dinner with my family"),
    ("social_contact", True, "en", "EN", "i met a friend for coffee"),
    ("social_contact", True, "en", "EN", "i called my brother today"),
    ("social_contact", False, "ar", "MSA", "لم أتحدث مع أحد اليوم"),
    ("social_contact", False, "ar", "MSA", "بقيت في البيت وحدي طوال اليوم"),
    ("social_contact", False, "ar", "GLF", "ما كلمت أحد اليوم"),
    ("social_contact", True, "ar", "MSA", "تناولت العشاء مع أهلي"),
    ("social_contact", True, "ar", "MSA", "قابلت صديقاً لشرب القهوة"),
    ("social_contact", True, "ar", "MSA", "اتصلت بأخي اليوم"),
]
